// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using poultry_management_system.web.Data;

#nullable disable

namespace poultry_management_system.web.Migrations
{
    [DbContext(typeof(PoultryDbContext))]
    [Migration("20241120042148_Initilize migration")]
    partial class Initilizemigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("poultry_management_system.web.Models.Domain.DialyFlockEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Avg_Weight")
                        .HasColumnType("int");

                    b.Property<int>("Daily_Eggs_Production")
                        .HasColumnType("int");

                    b.Property<int>("Feed_Consume")
                        .HasColumnType("int");

                    b.Property<string>("Health_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mortallity")
                        .HasColumnType("int");

                    b.Property<int>("Opening_Birds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
